### ISSUE TITLE
example

### ISSUE THREAD

**Issue by bugmind** [Quinton/node-apollo#5]
example不能直接运行啊
```
> apollo_docker_web_app@1.0.0 start /Users/xuyanan/code/node-apollo/example
> node server.js

/Users/xuyanan/code/node-apollo/example/node_modules/node-apollo/lib/apollo.js:11
  remoteConfigService: async (config) => {
                             ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xuyanan/code/node-apollo/example/node_modules/node-apollo/index.js:3:18)
    at Module._compile (module.js:571:32)

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! apollo_docker_web_app@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the apollo_docker_web_app@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the apollo_docker_web_app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs apollo_docker_web_app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls apollo_docker_web_app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xuyanan/code/node-apollo/example/npm-debug.log
```

**Comment by bugmind** [comment]
原来是node版本没升级，更新之后就好了
